version: '3.4'

services:
  llama2api:
    image: llama2api
    volumes:
      - "./models:/app/models"
    build:
      context: .
      dockerfile: ./Dockerfile.Instruct
    ports:
      - 5001:5001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
